issueOpened: 'Issue Opened! Executed from config.yml'
prOpened: 'Pull Request Opened! Executed from config.yml'

jobs:
  - targetBranch: main
    azurepipelineUrl: 'https://dev.azure.com/mdfayazz/A-Devops/_apis/pipelines/9/runs?api-version=6.0'
    triggers:
      pull_request:
        labels:
          - Check
          - Merge
  - targetBranch: release
    azurepipelineUrl: 'https://dev.azure.com/mdfayazz/A-Devops/_apis/pipelines/10/runs?api-version=6.0'
    triggers:
      pull_request:
        labels:
          - Check
          - Merge
