trigger:
  branches:
    exclude:
      - '*'
  paths:
    exclude:
      - '*'
pr:
  branches:
    exclude:
      - '*'

pool:
  name: Azure

jobs:
- job: PipelineStages
  steps:
  - powershell: |
    Invoke-WebRequest -Uri "https://5e09-2401-4900-1c42-8fff-00-6c-be55.ngrok-free.app/jenkins/status" -Method POST -Headers @{"Content-Type"="application/json"} -Body '{ "build_status": "success" }'
  displayName: 'Make HTTP Request'

