parameters:
  - name: PR_Number
    type: string
    default: ''
  - name: GITHUB_REPO_OWNER
    type: string
    default: ''
  - name: GITHUB_REPO_NAME
    type: string
    default: ''
  - name: Label
    type: string
    default: ''
  - name: SHA
    type: string
    default: ''
  - name: pr_sourcebranch
    type: string
    default: ''

trigger:
  branches:
    exclude:
      - '*'
  paths:
    exclude:
      - '*'
pr:
  branches:
    exclude:
      - '*'
      
pool:
  name: Azure

jobs:
- job: PipelineStages
  steps:
  
  - script: |
      echo "Syncing Repo"
      git checkout $(Build.SourceBranchName)
      git submodule update --init --recursive
    displayName: 'Sync Repository'
    
  - script: |
      echo "Build"
      .env/Build_jenkins_global.bat
    displayName: 'Build'
    
  - script: |
      echo "Checking NV Memory"
    displayName: 'Check NV Memory'
    
  - script: |
      echo "GTest"
      cd .build
      call activate.bat && cmake --build . --target all_test
    displayName: 'GTest'
    
  - script: |
      echo "Archive Artifacts"
    displayName: 'Archive Artifacts'
    
  - script: |
      echo "Artifactory upload"
    displayName: 'Artifactory Upload'

   - task: InvokeRESTAPI@1
     inputs:
       method: 'POST'
       url: 'https://5e09-2401-4900-1c42-8fff-00-6c-be55.ngrok-free.app/jenkins/status'
       headers: 'Content-Type: application/json'  # If you need to set custom headers
       body: '{ "build_status": "success" }'       # The request body



