parameters:
  - name: PR_Number
    type: string
    default: ''
  - name: GITHUB_REPO_OWNER
    type: string
    default: ''
  - name: GITHUB_REPO_NAME
    type: string
    default: ''
  - name: Label
    type: string
    default: ''
  - name: SHA
    type: string
    default: ''
  - name: pr_sourcebranch
    type: string
    default: ''
  - name: RELEASE_TAG
    type: string
    default: ''

trigger:
  branches:
    exclude:
      - '*'
  paths:
    exclude:
      - '*'
pr:
  branches:
    exclude:
      - '*'

pool:
  name: Azure

jobs:
- job: AllStages
  steps:
  - script: |
      echo "Building SW"
      .env/Build_jenkins_global.bat
    displayName: 'Build'

  - script: |
      echo "Checking NV Memory"
    displayName: 'Parallel'

  - script: |
      echo "Testing...."
    displayName: 'Build Verification Test'

  - script: |
      cd .build
      call activate.bat && cmake --build . --target all_test
    displayName: 'GTest'

  - script: |
        echo "Archiving the Repository.."
        tar -cvzf release.tar.gz .
    displayName: 'Archive'

  - script: |
        $releaseTag = $env:RELEASE_TAG
        $releaseTagLower = $releaseTag.ToLower()
        echo "Building Docker Image"
        docker build -t $releaseTagLower:$releaseTag ./
    displayName: 'Building Docker Image'

  - script: |
        $releaseTag = $env:RELEASE_TAG
        $releaseTagLower = $releaseTag.ToLower()
        echo "Releasing the Docker Container"
        aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 913376974711.dkr.ecr.eu-north-1.amazonaws.com
        docker tag $releaseTagLower:$releaseTag 913376974711.dkr.ecr.eu-north-1.amazonaws.com/ad_steering_control:$releaseTag
        docker push 913376974711.dkr.ecr.eu-north-1.amazonaws.com/ad_steering_control:$releaseTag
    displayName: 'Release'
  - script: |
      echo "URL: https://5e09-2401-4900-1c42-8fff-00-6c-be55.ngrok-free.app/jenkins/status"
      echo "JSON Data: { \"build_status\": \"success\" }"
      (curl -X POST -H "Content-Type: application/json" -d "{ \"build_status\": \"success\" }" https://5e09-2401-4900-1c42-8fff-00-6c-be55.ngrok-free.app/jenkins/status --max-time 10) || exit 0
    displayName: 'Sending Status'
